import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { ThemeProvider } from 'styled-components'
import styles from '../styles/Home.module.css'
import Card from '../components/Card/Card'
import theme, { MyGlobalStyle } from '../theme/theme';

const Home: NextPage = () => {
  const meetingDate = {
    time: new Date(2022, 11, 24, 0, 0, 0, 0),
    from: new Date(2022, 11, 24, 11, 0, 0, 0),
    to: new Date(2022, 11, 24, 2, 0, 0, 0),
  }
  const attendees = [{
    id: 'id-one',
    img: 'https://picsum.photos/200'
  },
  {
    id: 'id-two',
    img: 'https://picsum.photos/200'
  },
  {
    id: 'id-three',
    img: 'https://picsum.photos/200'
  }]
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <ThemeProvider theme={theme}>
          <MyGlobalStyle />
          <Card
            title='Meeting Title'
            description='Project'
            location='online'
            date={meetingDate}
            attendees={attendees}
            status='scheduled'
          />


        </ThemeProvider>
      </main>

    </div>
  )
}

export default Home
